### PR TITLE
Remove "http://www.wikidata.org/.well-known" values 

### PR DESCRIPTION
**Pull request by naresh-kumar-babu**
Strange "http://www.wikidata.org/.well-known" values (these may be “blank nodes”) sometimes show up; these should not be displayed

### CODE REVIEW

**Comment by sahajk21** [comment]
Instead of hardcoding it, you can add a config variable like BLACKLISTED_VALUES= [] and then remove them.

**Comment by yaronkoren** [comment]
I agree that "wikidata.org" should not be hardcoded there. But what about just looking for strings containing ".well-known"? It seems pretty straightforward that such values should be ignored, while everything else should be kept - I can't think of a reason why someone would want a rule different from this.

**Comment by sahajk21** [comment]
I think that instead of hard-coding values like “.well-known” into the code, it would be better to have a global list of blacklisted values. This way, we can handle other cases that may arise in the future.
But if you think ".well-known" is a very specific case, we can go ahead with the change.

**Comment by yaronkoren** [comment]
It's true that more such strings could appear in the future - and the developers of Wikibase could also change ".well-known" at any time to something else. Still, I think until something like that happens, hardcoding this is fine - I'm going by the "YAGNI principle" here:

https://en.wikipedia.org/wiki/You_aren't_gonna_need_it

**Review by sahajk21 — CHANGES_REQUESTED** [review]
Let's go ahead with the change. But we should combine the two filter statements.

**Review by sahajk21 — APPROVED** [review]
Looks good

**Pull request merged**
