### PR TITLE
Change arrow direction in Apply filter

### PR DESCRIPTION
**Pull request by naresh-kumar-babu**
Arrows in "Apply filter" box seem like they're pointing the wrong way - right now it’s ▼ when minimized and ▲ when maximized, but it seems like it should be 🞂 when minimized and ▼ when maximized

### CODE REVIEW

**Comment by sahajk21** [comment]
This is a bit confusing change. Since the arrow is positioned to the left of the head, I suppose a side arrow won't be a good UI.

**Comment by yaronkoren** [comment]
@sahajsk21 - right for minimized and down for maximized does seem to have become a more standard approach than down/up - see the responses here:

https://ux.stackexchange.com/questions/5735/which-way-should-arrows-point-in-a-collapsible-accordion-left-down-down-up

Do you disagree with right/down in general, or do you just think this specific patch should be improved?

(By the way, one issue I see now with this patch is that, if it's going to be a sideways arrow, it should point left instead for right-to-left languages.)

**Comment by sahajk21** [comment]
I agree with the right/down convention. It would although be better to have the arrow on the other end of the "Apply filter ..." text.
image

Also we are using this arrow in the language dropdown in the navbar as well. I suppose that needs to be changed as well.

**Comment by yaronkoren** [comment]
That's interesting. I have some questions/comments:

- Why do you think the arrow thing would be better on the right?
- Would the arrow then point left, or would it still point right?
- What about for RTL languages?
- Maybe the language selector needs to change to match it - I never really even noticed that before. These do feel a little different because the language selector pops up a new window, vs. just minimizing/maximizing text. But I'm really not sure any more about any of this.

**Comment by sahajk21** [comment]
### Reasons
1. Personal thoughts: Arrows alongside text generally feel better with tree like dropdowns. With accordions it looks better on the other end.
2. Conventions: CSS frameworks like bootstrap use arrow on the right, so it would align with other common websites.

### Behaviour
Right on closed and down on open.
For RTL languages, arrow on the left end and the text on the right.

### Language Selector
I would suggest no rotation at all. Let it always point downwards. I checked few websites (including Wikipedia) which use this for similar dropdowns.

**Comment by yaronkoren** [comment]
Okay, everything you wrote makes sense. Given that, maybe the only other thing that needs to be done in this patch is to move the arrow to the other side. RTL support should be fine already - the layout will get flipped automatically, and I think it's fine (at least for now) if the arrow points right for those languages as well.

Keeping the language selector always pointing down seems like a good idea, although it's probably best done in a separate patch.

**Comment by sahajk21** [comment]
@yaronkoren Sounds good.
@TechieNK Please go ahead and make the changes.

**Pull request merged**
