### PR TITLE
Fix filter retainment in URL parameters

### LINKED ISSUE #39: Selected filter values stay in "memory" even after you hit the back button
There are many ways to replicate this problem, but here is one. From the main page:
- click "Film"
- click "country of origin"
- click "Italy"
- hit "back"
- hit "back"
- click "director"

The display looks fine, but the URL now contains an extra "f.P495=Q38" - and will to continue to hold this string as you keep clicking on things. Which is not good, because then if you reload the page at any point, the "country of origin: Italy" filter will get added back in to the display.

### PR DESCRIPTION
**Pull request by naresh-kumar-babu**
Fixes #39 .

### CODE REVIEW

**Comment by yaronkoren** [comment]
This works on Wikidata Walkabout! @sahajsk21 - what do you think?

**Review by sahajk21 — CHANGES_REQUESTED** [review]
Please combine the three if statements into one. The rest looks good.

**Review by sahajk21 — CHANGES_REQUESTED** [review]
Please combine e.state of statement as well.

**Comment by yaronkoren** [comment]
Are you sure? That first "if" check has other code that gets called.

**Comment by sahajk21** [comment]
My bad. The outer if has other code that is independent of the two conditions.
Merged.

**Pull request merged**
