### PR TITLE
Sort Single Page values

### PR DESCRIPTION
**Pull request by naresh-kumar-babu**

### CODE REVIEW

**Comment by sahajk21** [comment]
Is Sparql not returning sorted results?
See [line 129](https://github.com/sahajsk21/Anvesha/blob/ec04198bf2bad5e0e0dfa4b889595d10c46dbf38/src/components/view-all-items.js#L129)

**Comment by yaronkoren** [comment]
@sahajsk21 - I think this worked before, but it no longer does, maybe due to the changing speeds of different queries. The problem now is that that line seems to always get called before this.totalValues is set - so the sorting is not added to the SPARQL. See here, for one of many examples:

https://wikidatawalkabout.org/?c=Q515&lang=en&r.P571=1001%7E1100

**Comment by sahajk21** [comment]
In that case I suppose the ORDER BY statement can be dropped altogether.

**Comment by yaronkoren** [comment]
That probably makes sense, yes.

**Comment by sahajk21** [comment]
@TechieNK Can you please drop totalValues as function parameter and access using "this" operator?

**Comment by naresh-kumar-babu** [comment]
@sahajsk21 Updated

**Pull request merged**
